version: '3.8'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  restaurant-service:
    build: ./restaurantService
    ports:
      - '3005:3005'
    depends_on:
      - rabbitmq

  dough-chef-service:
    build: ./doughChefService
    deploy:
      replicas: 2
#    ports:
#      - '3001:3001'
    depends_on:
      - rabbitmq

  topping-chef-service:
    build: ./toppingChefService
    deploy:
      replicas: 3
#    ports:
#      - '3002:3002'
    depends_on:
      - rabbitmq

  oven-service:
    build: ./ovenService
#    ports:
#      - '3003:3003'
    depends_on:
      - rabbitmq

  waiter-service:
    build: ./waiterService
    deploy:
      replicas: 2
#    ports:
#      - '3004:3004'
    depends_on:
      - rabbitmq

  reporter-service:
    build: ./reporterService
    #    ports:
    #      - '3006:3006'
    depends_on:
      - rabbitmq